services:
  postgres:
    image: postgres:16-alpine
    container_name: hefesto-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: hefesto
      POSTGRES_PASSWORD: hefesto
      POSTGRES_DB: hefesto
    ports:
      - '5432:5432'
    volumes:
      - hefesto-pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U hefesto -d hefesto']
      interval: 5s
      timeout: 5s
      retries: 5

  adminer:
    image: adminer:4
    container_name: hefesto-adminer
    restart: unless-stopped
    ports:
      - '8080:8080'
    depends_on:
      - postgres

volumes:
  hefesto-pgdata:
